/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Datos.ProductoData;
import Entidades.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author consu
 */
public class ProductosVista extends javax.swing.JInternalFrame {

    private ArrayList<Producto>proArray=new ArrayList<>();
    private ProductoData proData=new ProductoData();
    
    private DefaultTableModel modelo=new DefaultTableModel(){
    public boolean isCellEditable(int fila, int columna){
        return false;
    }
    };
    public ProductosVista() {
        initComponents();
        BuscarCategoria.setEnabled(false);
        BuscarMarca.setEnabled(false);
        armarCabecera();
        cargarCombo();
        TextoProducto.setText("");
        cargarDatos();
        TextoCategoria.toString().substring(0).toUpperCase();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcAgregar = new javax.swing.JRadioButton();
        OpcEditar = new javax.swing.JRadioButton();
        OpcEliminar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextoCodigo = new javax.swing.JTextField();
        TextoCategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ComboCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TextoMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextoDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoProducto = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        BotonCancelar = new javax.swing.JButton();
        BotonAceptar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TextoPrecio = new javax.swing.JTextField();
        ComboMarca = new javax.swing.JComboBox<>();
        BuscarCategoria = new javax.swing.JButton();
        BuscarMarca = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();

        OpcAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OpcAgregar.setText("AGREGAR");
        OpcAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcAgregarActionPerformed(evt);
            }
        });

        OpcEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OpcEditar.setText("EDITAR");
        OpcEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcEditarActionPerformed(evt);
            }
        });

        OpcEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OpcEliminar.setText("ELIMINAR");
        OpcEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("SELECCIONE UNA OPCION");

        jLabel2.setText("CODIGO");

        jLabel3.setText("CATEGORIA");

        TextoCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextoCategoriaKeyReleased(evt);
            }
        });

        jLabel4.setText("BUSCAR CATEGORA");

        jLabel5.setText("PRECIO");

        jLabel6.setText("DESCRIPCION");

        jLabel7.setText("MARCA");

        TextoProducto.setColumns(20);
        TextoProducto.setRows(5);
        jScrollPane1.setViewportView(TextoProducto);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("PRODUCTO");

        BotonCancelar.setText("CANCELAR");

        BotonAceptar.setText("ACEPTAR");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        jLabel9.setText("BUSCAR MARCA");

        BuscarCategoria.setText("BUSCAR");

        BuscarMarca.setText("BUSCAR");
        BuscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMarcaActionPerformed(evt);
            }
        });

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OpcAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OpcEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OpcEliminar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextoCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(TextoCodigo, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoMarca)
                            .addComponent(TextoDescripcion)
                            .addComponent(TextoPrecio)
                            .addComponent(ComboMarca, 0, 157, Short.MAX_VALUE)
                            .addComponent(ComboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarCategoria)
                            .addComponent(BuscarMarca)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonCancelar)
                                .addGap(83, 83, 83)
                                .addComponent(BotonAceptar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonCancelar)
                            .addComponent(BotonAceptar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OpcAgregar)
                            .addComponent(OpcEditar)
                            .addComponent(OpcEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(ComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BuscarMarca))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(TextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcAgregarActionPerformed
        OpcEditar.setSelected(false);
        OpcEliminar.setSelected(false);
        TextoCodigo.setEditable(false);
        BuscarCategoria.setEnabled(false);
        BuscarMarca.setEnabled(false);
        TextoCodigo.setText("");
        int contador=1;        
        proArray=proData.listarProductos();
        if(proArray.isEmpty()){
            TextoCodigo.setText("1");
        }else{
            for (Producto producto : proArray) {
                if(producto.getCodigoProducto()==contador){
                    contador++;
                }else{
                    TextoCodigo.setText(contador+"");
                    break;
                }
            }
        }       
    }//GEN-LAST:event_OpcAgregarActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        String categoria=TextoCategoria.getText();
        String marca=TextoMarca.getText();
        String descripcion=TextoDescripcion.getText();
        String pre=TextoPrecio.getText();
        Producto producto=new Producto();
        if(categoria.isEmpty()||marca.isEmpty()||descripcion.isEmpty()||pre.isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        }else{
            if(OpcAgregar.isSelected()){
            try{
                double precio=Double.parseDouble(pre);
                producto.setCategoria(categoria);
                producto.setMarca(marca);
                producto.setDescripcion(descripcion);
                producto.setPrecio(precio);
                proData.cargarProducto(producto);
            }catch(NumberFormatException x){
                JOptionPane.showMessageDialog(null, "Debe colocar solo numeros en el campo de precio");
            }
        }else if(OpcEditar.isSelected()){
            
        }
        }
        
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void OpcEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcEditarActionPerformed
        OpcAgregar.setSelected(false);
        OpcEliminar.setSelected(false);
        BuscarCategoria.setEnabled(true);
        BuscarMarca.setEnabled(true);
        TextoCodigo.setText("");
        
        
    }//GEN-LAST:event_OpcEditarActionPerformed

    private void BuscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarMarcaActionPerformed

    private void OpcEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcEliminarActionPerformed
        OpcAgregar.setSelected(false);
        OpcEditar.setSelected(false);
        TextoCodigo.setText("");
        BuscarCategoria.setEnabled(true);
        BuscarMarca.setEnabled(true);
    }//GEN-LAST:event_OpcEliminarActionPerformed

    private void TextoCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoCategoriaKeyReleased
        
        String leer=TextoCategoria.getText().toLowerCase();
        int largo=leer.length();
        String letra=" ";
        String frase=" ";
        for (int i = 0; i < largo; i++) {
            if(i==0){
                if(leer.substring(i).equals(" ")){
                    JOptionPane.showMessageDialog(null, "No puede ingresar un espacio como primer caracter");
                    TextoCategoria.setText("");
                }else{
                    letra=leer.substring(0, 1).toUpperCase();
                   
                    TextoCategoria.setText(letra);
                }
            }else{
                frase=letra+leer.substring(1);
                TextoCategoria.setText(frase);
            }
        }
        cargarDatos();
//        cargarDatos();
//        String leer=TextoCategoria.getText().toLowerCase();
//        leer.substring(0).toUpperCase();
//        int largo=leer.length();
//        if(largo==1){
//            if(leer.substring(0).equals(" ")){
//            JOptionPane.showMessageDialog(null, "Ingrese un caracter valido");
//            TextoCategoria.setText("");
//        }else {
//                leer.toUpperCase();
//                TextoCategoria.setText(leer);
//            }
//        }
        
            
    }//GEN-LAST:event_TextoCategoriaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BuscarCategoria;
    private javax.swing.JButton BuscarMarca;
    private javax.swing.JComboBox<String> ComboCategoria;
    private javax.swing.JComboBox<String> ComboMarca;
    private javax.swing.JRadioButton OpcAgregar;
    private javax.swing.JRadioButton OpcEditar;
    private javax.swing.JRadioButton OpcEliminar;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTextField TextoCategoria;
    private javax.swing.JTextField TextoCodigo;
    private javax.swing.JTextField TextoDescripcion;
    private javax.swing.JTextField TextoMarca;
    private javax.swing.JTextField TextoPrecio;
    private javax.swing.JTextArea TextoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
public void cargarCombo(){
    proArray=proData.listarProductos();
    ComboCategoria.addItem("Categoria");
    ComboMarca.addItem("Marca");
    for (Producto producto : proArray) {
        ComboCategoria.addItem(producto.getCategoria());
        ComboMarca.addItem(producto.getMarca());
    }
}
private void armarCabecera(){
    modelo.addColumn("codigo");
    modelo.addColumn("Categoria");
    modelo.addColumn("Marca");
    modelo.addColumn("Descripcion");
    TablaProductos.setModel(modelo); 
}
private void cargarDatos(){    
    TextoProducto.setText("");
    String cod=TextoCodigo.getText();
    String marca=TextoMarca.getText();
    String categoria=TextoCategoria.getText();
    String descripcion=TextoDescripcion.getText();
    String precio=TextoPrecio.getText();
    
    
    
    TextoProducto.append("Codigo : "+cod+"\n"+"Categoria: "+categoria+"\n"+" Marca: "+marca+"\n"+"Descripcion :"
            + ""+descripcion+"\n"+"Precio :"+precio);

}


}
